### ISSUE TITLE
Make Helping Direction for new user.

### ISSUE THREAD

**Issue by Thidtanai** [ChayanonPitak/Uics#21]

**Comment by Thidtanai** [comment]
I will send asset into Microsoft team  General>Asset>Help Direction

**Comment by Thidtanai** [comment]
I'm added asset.

**Comment by IkaWaAyuMu** [comment]
Still need detailed help on each section.

[469b2dc](https://github.com/ChayanonPitak/Uics/commit/469b2dc899385130f3934d89cdaef4a700fdc497) has added prototype help panel.

**Comment by Thidtanai** [comment]
I think having that is enough because another section use the same. But I can make more if you want 😃 .

**Comment by IkaWaAyuMu** [comment]
I think there is lack on detail.
It should hae detail on each section for what does that do.

**Comment by Thidtanai** [comment]
Ok,I got it 🙆‍♂️ .

**Comment by Thidtanai** [comment]
I'm added all asset in microsoft team. 🤟
